version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: payengine-server
    build:
      context: ./
      dockerfile: dockerfile
      args:
        nodenv: production
        pgconnstr: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports: 
     - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PG_CONNECTION_STRING: postgresql://postgres:postgres@db:5432/postgres
      PRIVATE_KEY: sk_test_gajKcTLEGpGQhPniCwvAQIRfhKiuGdRD05hvlPqmABO62xcOH6UP3EDkn69qSnsUbWPjkq37mavXQzBsN05CXk9nF0OZWH7nFt9Q

    links:
      - db
  
 

volumes:
  db:
    driver: local
